// Guard: the two generated Capacitor gradle files must stay in sync.
//
// `android/app/capacitor.build.gradle` lists each plugin as
//   implementation project(':capacitor-x')
// and `android/capacitor.settings.gradle` must carry a matching
//   include ':capacitor-x'
// (android/settings.gradle applies capacitor.settings.gradle, and that is the
// ONLY place plugin projects get included). Gradle resolves the dependency at
// CONFIGURATION time, so a missing include is not a soft warning — the whole
// build dies before compiling anything:
//
//   Script 'android/app/capacitor.build.gradle' line: 17
//   Project with path ':capacitor-haptics' could not be found in project ':app'.
//   BUILD FAILED
//
// That is exactly what happened on main after the haptics work (PRs #1170/#1171)
// added @capacitor/haptics: build.gradle gained the `implementation` line but
// settings.gradle never gained the `include`, so `./gradlew bundleRelease` —
// the documented Play-launch step — could not configure at all.
//
// Both files are generated by `npx cap sync android`, but they are TRACKED, so
// a half-synced commit breaks every clean checkout until someone re-syncs.
// This test compares the two committed files directly and needs no Android SDK.

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '../..');
const buildGradle = readFileSync(join(repoRoot, 'android/app/capacitor.build.gradle'), 'utf8');
const settingsGradle = readFileSync(join(repoRoot, 'android/capacitor.settings.gradle'), 'utf8');

/** Plugin projects declared as dependencies of :app. */
const declaredDeps = [...buildGradle.matchAll(/implementation\s+project\('(:[\w-]+)'\)/g)]
  .map(m => m[1]);

/** Plugin projects included in the settings file. */
const includedProjects = [...settingsGradle.matchAll(/include\s+'(:[\w-]+)'/g)]
  .map(m => m[1]);

/** Projects given an explicit projectDir. */
const withProjectDir = [...settingsGradle.matchAll(/project\('(:[\w-]+)'\)\.projectDir/g)]
  .map(m => m[1]);

describe('capacitor gradle files stay in sync', () => {
  it('parses both generated files (guard is live)', () => {
    expect(declaredDeps.length).toBeGreaterThan(3);
    expect(includedProjects.length).toBeGreaterThan(3);
  });

  it('every plugin :app depends on is included in settings.gradle', () => {
    const missing = declaredDeps.filter(p => !includedProjects.includes(p));
    expect(
      missing,
      `capacitor.build.gradle declares ${missing.join(', ')} but capacitor.settings.gradle ` +
      `never includes it — Gradle fails at configuration time with ` +
      `"Project with path '${missing[0]}' could not be found in project ':app'". ` +
      `Run \`npx cap sync android\` and commit BOTH files.`
    ).toEqual([]);
  });

  it('every included plugin project also gets a projectDir', () => {
    // `include` without a projectDir points Gradle at a non-existent default
    // path. capacitor-android is the one legitimate exception — it is included
    // by the Capacitor scaffold itself.
    const missingDir = includedProjects
      .filter(p => p !== ':capacitor-android')
      .filter(p => !withProjectDir.includes(p));
    expect(missingDir, `included without a projectDir: ${missingDir.join(', ')}`).toEqual([]);
  });

  it('does not include plugin projects that :app never depends on', () => {
    // A stale include left behind after a plugin is removed points at a
    // node_modules path that no longer exists.
    const orphaned = includedProjects
      .filter(p => p !== ':capacitor-android')
      .filter(p => !declaredDeps.includes(p));
    expect(orphaned, `included but unused: ${orphaned.join(', ')}`).toEqual([]);
  });
});
