// src/api/referralApi.js
//
// Referral backend via Supabase RPC functions (SECURITY DEFINER).
// All writes go through rate-limited Postgres functions — never direct
// table access. See sql/api-security-hardening.sql.

import { supabase } from '@/lib/supabaseClient';
import { isDeniabilityOrDemoActive } from '@/wallet-core/deniabilitySession';
import { getOrCreateDeviceId } from '@/lib/deviceId';

// Referral codes are generated by sql/api-security-hardening.sql:
// 'VYX-' prefix + 6 chars from the Crockford-base32 alphabet (no I/O/1/0).
const REFERRAL_CODE_RE = /^VYX-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$/;
function isValidCode(code) {
  return typeof code === 'string' && REFERRAL_CODE_RE.test(code);
}

// H-1 (2026-07-28): rc_user_id is no longer sent from the client. Earlier
// revs passed getAppUserId() into generate_referral_code / register_referral_code,
// which let anyone with the app bundle's public anon key bind an arbitrary
// RevenueCat identity to a referral code and mint a promotional entitlement
// against it. The identity is now set server-side from a verified RevenueCat
// webhook (see sql/referral-rc-webhook.sql). Until that webhook is deployed
// the first-referral bonus path is inert — check_first_referral_bonus returns
// NULL when rc_user_id is unset (I4: fail closed).
export async function generateServerCode() {
  if (!supabase || isDeniabilityOrDemoActive()) return null;
  try {
    const deviceId = getOrCreateDeviceId();
    if (!deviceId) return null;
    const { data, error } = await supabase.rpc('generate_referral_code', {
      p_device_id: deviceId,
    });
    if (error || !data) return null;
    return data;
  } catch {
    return null;
  }
}

export async function registerCode(code) {
  if (!isValidCode(code)) return;
  if (!supabase || isDeniabilityOrDemoActive()) return;
  try {
    const deviceId = getOrCreateDeviceId();
    await supabase.rpc('register_referral_code', {
      p_code: code,
      p_device_id: deviceId,
    });
  } catch {
    // Best-effort: silently ignore network/db failures on register.
  }
}

export async function redeemCode(code) {
  if (!isValidCode(code)) throw Object.assign(new Error('Invalid code format'), { status: 400 });
  if (isDeniabilityOrDemoActive()) throw Object.assign(new Error('Unavailable'), { status: 503 });
  if (!supabase) throw Object.assign(new Error('No referral backend configured'), { status: 503 });

  const deviceId = getOrCreateDeviceId();
  if (!deviceId) throw Object.assign(new Error('No device ID'), { status: 500 });

  const { data, error } = await supabase.rpc('increment_referral', {
    p_code: code,
    p_device_id: deviceId,
  });

  if (error) {
    if (error.code === 'P0001' || error.message?.includes('not found')) {
      throw Object.assign(new Error('Code not found'), { status: 404 });
    }
    throw Object.assign(new Error(error.message || 'Referral error'), { status: 500 });
  }

  return { newCount: data };
}

// Reads the code's redemption count through an RPC rather than selecting from
// `referrals` directly. This was the last direct table read in the client, and
// it is what kept the `public select using (true)` policy alive — a policy that
// is row-level, so it exposed EVERY column of that table to anon, including
// device_id and rc_user_id, which were added long after the policy's "no
// sensitive data" justification was written. See sql/referrals-select-lockdown.sql.
//
// `data` is now a bare integer, so the guard is `data == null` rather than
// `!data`: a count of 0 is a real value the tracker renders, not a miss.
export async function fetchStatus(code) {
  if (!isValidCode(code)) return null;
  if (!supabase || isDeniabilityOrDemoActive()) return null;
  try {
    const { data, error } = await supabase.rpc('get_referral_count', {
      p_code: code,
    });
    if (error || data == null) return null;
    return { count: data };
  } catch {
    return null;
  }
}

export const fetchReferrerTier = fetchStatus;

export async function fetchPaidCount(code) {
  if (!isValidCode(code)) return null;
  if (!supabase || isDeniabilityOrDemoActive()) return null;
  try {
    const { data, error } = await supabase.rpc('get_referral_paid_count', {
      p_code: code,
    });
    if (error || data == null) return null;
    return data;
  } catch {
    return null;
  }
}

export async function recordAttribution(referralCode, plan, revenueCents, discountCents) {
  if (!isValidCode(referralCode)) return;
  if (!supabase || isDeniabilityOrDemoActive()) return;
  try {
    await supabase.rpc('record_attribution', {
      p_code: referralCode,
      p_plan: plan,
      p_revenue_cents: revenueCents,
      p_discount_cents: discountCents || 0,
    });
  } catch {
    // Best-effort: don't block the purchase flow on attribution failure.
  }
}

export async function fetchEarnings(code) {
  if (!isValidCode(code)) return null;
  if (!supabase || isDeniabilityOrDemoActive()) return null;
  try {
    const { data, error } = await supabase.rpc('get_referral_earnings', {
      p_code: code,
    });
    if (error || !data) return null;
    return data;
  } catch {
    return null;
  }
}

export async function claimFirstReferralBonus(referralCode) {
  if (!isValidCode(referralCode)) return null;
  if (!supabase || isDeniabilityOrDemoActive()) return null;
  try {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
    const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
    if (!supabaseUrl || !supabaseKey) return null;

    const res = await fetch(
      `${supabaseUrl}/functions/v1/first-referral-bonus`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${supabaseKey}`,
        },
        body: JSON.stringify({ referral_code: referralCode }),
      },
    );
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}
