// src/api/referralApi.js
//
// Referral backend via Supabase RPC functions (SECURITY DEFINER).
// All writes go through rate-limited Postgres functions — never direct
// table access. See sql/api-security-hardening.sql.

import { rpc, edgeFn } from '@/api/edgeApi';
import { isDeniabilityOrDemoActive } from '@/wallet-core/deniabilitySession';
import { getOrCreateDeviceId } from '@/lib/deviceId';
import { encodeAttributionPlan } from '@/lib/referral';

// Referral codes are generated by sql/api-security-hardening.sql:
// 'VYX-' prefix + 6 chars from the Crockford-base32 alphabet (no I/O/1/0).
const REFERRAL_CODE_RE = /^VYX-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$/;
function isValidCode(code) {
  return typeof code === 'string' && REFERRAL_CODE_RE.test(code);
}

// H-1 (2026-07-28): rc_user_id is no longer sent from the client. Earlier
// revs passed getAppUserId() into generate_referral_code / register_referral_code,
// which let anyone with the app bundle's public anon key bind an arbitrary
// RevenueCat identity to a referral code and mint a promotional entitlement
// against it. The identity is now set server-side from a verified RevenueCat
// webhook (see sql/referral-rc-webhook.sql). Until that webhook is deployed
// the first-referral bonus path is inert — check_first_referral_bonus returns
// NULL when rc_user_id is unset (I4: fail closed).
export async function generateServerCode() {
  if (isDeniabilityOrDemoActive()) return null;
  try {
    const deviceId = getOrCreateDeviceId();
    if (!deviceId) return null;
    const data = await rpc('generate_referral_code', {
      p_device_id: deviceId,
    });
    if (!data) return null;
    return data;
  } catch {
    return null;
  }
}

// Codex P2 2026-08-15: returns the code the SERVER actually registered, so a
// caller whose client-supplied code collided with an existing row (previously
// silently dropped by ON CONFLICT DO NOTHING) can reconcile its local state
// to whatever the server minted server-side. Returns null on rate-limit,
// deniability, network failure, or an exhausted server-retry loop.
export async function registerCode(code) {
  if (!isValidCode(code)) return null;
  if (isDeniabilityOrDemoActive()) return null;
  const deviceId = getOrCreateDeviceId();
  if (!deviceId) return null;
  try {
    const data = await rpc('register_referral_code', {
      p_code: code,
      p_device_id: deviceId,
    });
    // SQL now returns text (the working code) or null; keep string-only.
    return typeof data === 'string' && isValidCode(data) ? data : null;
  } catch {
    // Best-effort: silently ignore network/db failures on register.
    return null;
  }
}

export async function redeemCode(code) {
  if (!isValidCode(code)) throw Object.assign(new Error('Invalid code format'), { status: 400 });
  if (isDeniabilityOrDemoActive()) throw Object.assign(new Error('Unavailable'), { status: 503 });

  const deviceId = getOrCreateDeviceId();
  if (!deviceId) throw Object.assign(new Error('No device ID'), { status: 500 });

  try {
    const data = await rpc('increment_referral', {
      p_code: code,
      p_device_id: deviceId,
    });
    return { newCount: data };
  } catch (err) {
    const e = /** @type {Error & {status?: number}} */ (err);
    if (e.status === 404 || e.message?.includes('not found')) {
      throw Object.assign(new Error('Code not found'), { status: 404 });
    }
    throw Object.assign(new Error(e.message || 'Referral error'), { status: 500 });
  }
}

// Reads the code's redemption count through an RPC rather than selecting from
// `referrals` directly. This was the last direct table read in the client, and
// it is what kept the `public select using (true)` policy alive — a policy that
// is row-level, so it exposed EVERY column of that table to anon, including
// device_id and rc_user_id, which were added long after the policy's "no
// sensitive data" justification was written. See sql/referrals-select-lockdown.sql.
//
// `data` is now a bare integer, so the guard is `data == null` rather than
// `!data`: a count of 0 is a real value the tracker renders, not a miss.
export async function fetchStatus(code) {
  if (!isValidCode(code)) return null;
  if (isDeniabilityOrDemoActive()) return null;
  try {
    const data = await rpc('get_referral_count', {
      p_code: code,
    });
    if (data == null) return null;
    return { count: data };
  } catch {
    return null;
  }
}

export const fetchReferrerTier = fetchStatus;

export async function fetchPaidCount(code) {
  if (!isValidCode(code)) return null;
  if (isDeniabilityOrDemoActive()) return null;
  // Strix H-2 / H-3 follow-up (2026-08-28): the owner-bound replacement for
  // paid-count reads is not deployed yet. Fail closed rather than expose
  // referral sales metadata through a public-code lookup.
  return null;
}

export async function recordAttribution(referralCode, planId, billingPeriod, revenueCents, discountCents) {
  if (!isValidCode(referralCode)) return;
  if (isDeniabilityOrDemoActive()) return;
  const encodedPlan = encodeAttributionPlan(planId, billingPeriod);
  if (!encodedPlan) return;
  void encodedPlan;
  void revenueCents;
  void discountCents;
  // Strix H-3 follow-up (2026-08-28): revenue attribution must be
  // server-authored. The client-callable RPC is disabled until the verified
  // webhook path is live, so purchases proceed without booking attribution.
}

export async function fetchEarnings(code) {
  if (!isValidCode(code)) return null;
  if (isDeniabilityOrDemoActive()) return null;
  // Strix H-2 / H-3 follow-up (2026-08-28): earnings must be scoped to the
  // referral owner, not a public referral code. Until that owner-bound server
  // path exists, suppress the read entirely.
  return null;
}

export async function claimFirstReferralBonus(referralCode) {
  if (!isValidCode(referralCode)) return null;
  if (isDeniabilityOrDemoActive()) return null;
  try {
    return await edgeFn('first-referral-bonus', { referral_code: referralCode });
  } catch {
    return null;
  }
}
