// G5 iOS RASP probe — runtime-registration + CI compile-verification pin tests.
//
// The ObjC RASP plugin (RaspIntegrityPlugin.m/Bridge.m) compiles and CAP_PLUGIN
// registers it as "RaspIntegrity" in the ObjC runtime. The gap is Capacitor 8's
// iOS bridge, which ONLY loads plugins listed in `capacitor.config.json →
// packageClassList` (regenerated by `cap sync` from npm packages, no runtime scan).
// After any `cap sync` the local plugin is silently dropped — JS calls throw
// "plugin is not implemented on ios" which nativeProbe catches → { available: false }
// → TIER.WARN (fail-closed, but the probe never runs).
//
// These tests pin:
//   1. register-local-ios-plugins.mjs includes 'RaspIntegrityPlugin' in
//      LOCAL_IOS_PLUGIN_CLASSES so `cap sync` never silently drops it.
//   2. ios-compile-check.yml asserts RaspIntegrityPlugin.o was produced (proves the
//      ObjC file compiled — the G5 analogue of the existing HardwareKekPlugin.o F5 check).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../../..');

// ── 1. Runtime registration ───────────────────────────────────────────────────

describe('G5 iOS RASP probe — runtime registration', () => {
  let src;

  beforeAll(() => {
    src = readFileSync(
      path.join(root, 'scripts/register-local-ios-plugins.mjs'),
      'utf8',
    );
  });

  it("LOCAL_IOS_PLUGIN_CLASSES includes 'RaspIntegrityPlugin'", () => {
    expect(src).toContain("'RaspIntegrityPlugin'");
  });

  it("LOCAL_IOS_PLUGIN_CLASSES array contains RaspIntegrityPlugin alongside existing entries", () => {
    const match = src.match(/const LOCAL_IOS_PLUGIN_CLASSES\s*=\s*\[([^\]]+)\]/s);
    expect(match).not.toBeNull();
    const classes = match[1];
    expect(classes).toContain("'RaspIntegrityPlugin'");
    expect(classes).toContain("'HardwareKekPlugin'");
  });
});

// ── 2. CI compile-verification ────────────────────────────────────────────────

describe('G5 iOS RASP probe — CI compile-verification', () => {
  let src;

  beforeAll(() => {
    src = readFileSync(
      path.join(root, '.github/workflows/ios-compile-check.yml'),
      'utf8',
    );
  });

  it('ios-compile-check.yml asserts RaspIntegrityPlugin.o was produced', () => {
    expect(src).toContain('RaspIntegrityPlugin.o');
  });
});
